version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  web:
    build: ./docker/web
    ports:
        - 8080:80
    environment:
      VIRTUAL_HOST: app.drupal.local
    volumes:
        - ./logs/nginx:/var/log/nginx/
        - drupal_volume:/var/www/html
        - ./app/web/modules:/var/www/html/web/modules
        - ./app/web/themes:/var/www/html/web/profiles
        - ./app/web/sites:/var/www/html/web/sites
        - ./app/web/themes:/var/www/html/web/themes
    depends_on:
        - app
  app:
    build: ./docker/app
    environment:
      PHP_INI_DIR: /etc/php7
      COMPOSER_PROCESS_TIMEOUT: 1000
    volumes:
      - drupal_volume:/var/www/html
      - ./app/web/modules:/var/www/html/web/modules
      - ./app/web/themes:/var/www/html/web/profiles
      - ./app/web/sites:/var/www/html/web/sites
      - ./app/web/themes:/var/www/html/web/themes
      - ./app/composer.json:/var/www/html/composer.json
      - ./app/composer.lock:/var/www/html/composer.lock
      - ./app/.editorconfig:/var/www/html/.editorconfig
      - ./app/.vscode:/var/www/html/.vscode
    depends_on:
        - db
        - mail
  db:
    image: mysql:5.7.16
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  mail:
    build: ./docker/mail
    environment:
      VIRTUAL_HOST: mail.laravel.local
    # ports:
    #   - "1080:80"
  dbclient:
    image: phpmyadmin/phpmyadmin
    environment:
      VIRTUAL_HOST: phpmyadmin.drupal.local
      MYSQL_DATABASE: app
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
        - db
    ports:
      - 8082:80
volumes:
  drupal_volume:
  mysql_volume: